import 'dart:io';
import 'dart:isolate';

/// The player a beacon build may hand its VM address to: its package and the
/// SHA-256 of its signing certificate, both as the player announces them.
typedef BeaconPlayer = ({String package, String certificate});

/// Bumped whenever the beacon's source changes, so a cached APK built with an
/// older beacon is rebuilt.
const beaconVersion = 1;

/// Builds the project's debug APK with the RHR beacon added (see
/// cli/android/rhr_beacon). The beacon is how the player learns the app's VM
/// service address without adb, so Wireless debugging is not needed.
///
/// Nothing in the project changes: the beacon module is copied under
/// `.dart_tool/rhr`, and an init script there includes it as a
/// `debugImplementation` dependency of this one build. `flutter build apk`
/// cannot take an init script, so this runs the project's Gradle wrapper,
/// which is what `flutter build` itself runs.
Future<File> buildBeaconDebugApk({
  required String project,
  required BeaconPlayer player,
  String? targetPlatform,
}) async {
  final root = Directory(project).absolute.path;
  final gradlew = File('$root/android/gradlew');
  if (!gradlew.existsSync()) {
    throw StateError(
      '$root/android/gradlew is missing. Run `flutter build apk --debug` once '
      'so Flutter restores the Gradle wrapper, then run rhr again.',
    );
  }
  final work = Directory('$root/.dart_tool/rhr');
  final module = Directory('${work.path}/rhr_beacon');
  if (module.existsSync()) module.deleteSync(recursive: true);
  await _copyDirectory(await _beaconSource(), module);

  final script = File('${work.path}/rhr_beacon.gradle')
    ..writeAsStringSync(beaconInitScript(module.path, player));
  final result = await Process.run(gradlew.path, [
    'assembleDebug',
    '--init-script',
    script.path,
    if (targetPlatform != null) '-Ptarget-platform=$targetPlatform',
  ], workingDirectory: '$root/android');
  if (result.exitCode != 0) {
    final output = '${result.stdout}\n${result.stderr}'.trim().split('\n');
    throw StateError(
      'Building the debug app with the RHR beacon failed:\n'
      '${output.skip(output.length > 40 ? output.length - 40 : 0).join('\n')}',
    );
  }
  for (final path in [
    '$root/build/app/outputs/flutter-apk/app-debug.apk',
    '$root/build/app/outputs/apk/debug/app-debug.apk',
  ]) {
    final apk = File(path);
    if (apk.existsSync()) return apk;
  }
  throw StateError('Gradle finished without producing app-debug.apk.');
}

/// The init script that includes the beacon module and tells it which player
/// to trust. Groovy, which every Gradle version reads as an init script.
String beaconInitScript(String modulePath, BeaconPlayer player) {
  String quoted(String value) =>
      "'${value.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";
  return '''
// Generated by rhr. Adds the RHR beacon to this debug build only; the project
// is untouched and release builds never contain it.
settingsEvaluated { s ->
    // Flutter's own Gradle plugin is an included build; only the app's
    // build gets the beacon.
    if (s.findProject(':app') == null) return
    s.include(':rhr_beacon')
    s.project(':rhr_beacon').projectDir = new File(${quoted(modulePath)})
}
allprojects { p ->
    p.plugins.withId('com.android.application') {
        p.android.defaultConfig.manifestPlaceholders.putAll([
            rhrPlayer: ${quoted(player.package)},
            rhrPlayerCertificate: ${quoted(player.certificate)},
        ])
        p.dependencies { add 'debugImplementation', p.project(':rhr_beacon') }
    }
}
''';
}

Future<Directory> _beaconSource() async {
  final library = await Isolate.resolvePackageUri(
    Uri.parse('package:rhr_cli/beacon_build.dart'),
  );
  if (library == null) throw StateError('cannot locate the rhr_cli package');
  final source = Directory.fromUri(library.resolve('../android/rhr_beacon/'));
  if (!source.existsSync()) {
    throw StateError('the RHR beacon source is missing from ${source.path}');
  }
  return source;
}

Future<void> _copyDirectory(Directory from, Directory to) async {
  await for (final entity in from.list(recursive: true)) {
    if (entity is! File) continue;
    final relative = entity.path.substring(from.path.length);
    if (relative.contains('/build/')) continue;
    final target = File('${to.path}/$relative');
    await target.parent.create(recursive: true);
    await entity.copy(target.path);
  }
}
